# -*- coding: utf-8 -*-
"""Request.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vd0lPPSFfuewjcghG6ZYpw8nDIAZKxoN
"""

import requests
r=requests.get('https://colab.research.google.com/drive/14rwuH15EQp9uVeekJyAHHVfhB_PaLmc-#scrollTo=orZk8-vZ1Zpq&line=30&uniqifier=1')
with open('request.txt','wb') as f:
    f.write(r.content)